apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    role: mysql
spec:
  containers:
  - name: mysql
    image: 772859080303.dkr.ecr.us-east-1.amazonaws.com/assignment_mysql:mysql
    ports:
    - containerPort: 3306
    env:
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
  imagePullSecrets:
  - name: regcred
